version: "3.9"

services:
  api-server:
    build: server
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: imdb
    expose:
      - "3001"
    depends_on:
      - db
    networks:
      - imdb-scrape

  # scraper expects a mysql db exposed on 3306
  scraper:
    build: scraper
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: imdb
    depends_on:
      - db
    networks:
      - imdb-scrape

  client:
    build: client
    ports:
      - "3000:3000"
    depends_on:
      - api-server
    networks:
      - imdb-scrape

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: imdb
      MYSQL_ROOT_HOST: "%"
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    networks:
      - imdb-scrape
    # maybe this is unnecessary because they're on the same network?
    # or because of the volumes thing?
    expose:
      - "3306"

networks:
  imdb-scrape:

volumes:
  db_data:
